# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'rspec', '3.11.0'
gem 'coderay', '1.1.3'
gem 'rack-test', '~> 1.1'
gem 'sinatra', '~> 2.2'
gem 'sequel', '~> 5.54'